### ISSUE TITLE
#thaycacac Lỗi hiển thị button "thêm KRs" sau khi thêm 1 Keyresults

### ISSUE THREAD

**Issue by quangnv281098** [Olympus-Team/OKRs-enterprise-frontend#193]
## Ở Firefox hoặc Safarir bình thường nhưng Chrome lại bị

![image](https://user-images.githubusercontent.com/56639191/90848967-60fdc780-e398-11ea-9197-d238f2321dcf.png)

**Comment by harrytran998** [comment]
I need helps @bacodekiller, @thaycacac  :)) Nó ở @/components/okrs/steps/addKrs/AddKeyResults.vue

Code thì như dưới, khi hover vào button thì nó sẽ fill vào SVG thành màu trắng!
```scss
 &__button {
    margin: $unit-4 0 $unit-4 0;
    &:hover,
    &:focus,
    &:active {
      span {
        svg {
          path {
            fill: $white;
          }
        }
      }
    }
 }
```
